version: '3.8'
services:
  learn-les01-init-lar-v11-db:
    image: mysql
    container_name: learn-les01-init-lar-v11-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678               # Set MySQL root password
      MYSQL_DATABASE: les01-init-lar-v11          # Set a default database
      MYSQL_USER: phucdn                          # Set a user for the database
      MYSQL_PASSWORD: 12345678                    # Password for the user
    ports:
      - "3314:3306"                               # Expose MySQL port to the host
    volumes:
      - db_data:/vat/lb/mysql                     # Persist MySQL data in a volume
    networks:
      - mynetwork

volumes:
  db_data:                                        # Define a volume to persist data

networks:
  mynetwork:                                      # Define a network for communication between services