version: "3.8"
services:
  server:
    image: "nginx:latest"
    ports:
      - "8222:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
      - ./dockerfiles/php.ini:/usr/local/etc/php/php.ini
  mysql:
    image: mysql:8.4.3
    environment:
      MYSQL_DATABASE: learnSetLaravelOnDockerB01
      MYSQL_USER: lSetLarB01
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3569:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html